def finding_motif_dna(s, t):
    if len(t) > len(s):
        raise Exception("Substing is longer than string")
    count = []
    for i in range(0, len(s) - len(t) - 1):
        if s[i:i+len(t)] == t:
            count.append(i + 1)
    return count

print(finding_motif_dna("TGTTGTATTAGAGGTTGTATGAGTTGTATTATGTTGTATAAAGAGTTGTATGAGAGTTGTATGTTGTTGTATGCCGTTGTATGTTGTATTCAGTTGTATGGTTGTATTATGGTTGTATGTTGTATCTCGTTGTATATCTGTTGTATCTGTTGTATACGTTGTATGTTGTATACGCTTCGGTTGGTTGTATGTTGTATAGGAAGTTGTATTAATGTTGTATTCAGTTGTATCGTTGTATGCGTTGTATCAGTTGTATGGGTTGTATTGTTGTATCGTTGTATGTTGTATGGTTGTATACAATTGTACGTTGTATCGTTGTATGCTCGCGTTGTATTAGCGTTGTATTAGCCGTTGTATAGTGTGAGGAGTTGTATGTATTAGTTGTATTCGTTGTATGTTGTATCTTGGTTGTATGTTGTATTGTAAGTTGTATGAGTAGACTGTTGTATGCACTGTTGTATAGTTGTATTCAGTGCGTTGTATTTGTTGTATCGTCAGGTTGTATAGAGTTGTATGTTGTATATGAGTTGTATTGTTGTATCCATTATGTTGTATAGTTGTATTGTTGTATAAAAGTTGTATGGTTGTATCGTTGTATTGTGTTGTATGCGTTGTATAGGGGGAGTTGTATCGTTGTATGTGTTGTATTGTTGTATAAAAGTTGTATTCAGGTTGTATACCTGTTGTATGTTGTATGTCAGTTGTATGTTGTATGTTGTATGCAGGTGTTGTATCAAGAAGTTGTATGTTGTATCGCCTAGGTCGTTGTATGTTGTATTGGAGTTGTATGTGTTGTATTGTTGTATAGGCTATAAGGTTGTATGTCCAGTTGTATGTTGTATAGTTGTATTGTTGTATCGA", "GTTGTATGT"))